/**:
  ros__parameters:
    wheel_radius: 0.12
    wheel_width: 0.42
    wheel_base: 1.087 # between front wheel center and rear wheel center
    wheel_tread: 1.0 # between left wheel center and right wheel center
    front_overhang: 0.7 # between front wheel center and vehicle front
    rear_overhang: 0.5 # between rear wheel center and vehicle rear
    left_overhang: 0.25 # between left wheel center and vehicle left
    right_overhang: 0.25 # between right wheel center and vehicle right
    vehicle_height: 0.6
    max_steer_angle: 1.39 # [rad]
